--------------------------------------------------------------------------------
Makelog started: 2019-10-21 17:49:31
Working directory: C:\Users\Zong\template\data
--------------------------------------------------------------------------------
******************************************************************************
* An error was encountered with `link_inputs`. Traceback can be found below. *
******************************************************************************

Traceback (most recent call last):
  File "C:\Users\Zong\template\lib\gslab_make\move_sources.py", line 202, in link_inputs
    source_map = _create_links(paths, file_list)
  File "C:\Users\Zong\template\lib\gslab_make\move_sources.py", line 49, in _create_links
    move_list = MoveList(file_list, move_dir, paths)
  File "C:\Users\Zong\template\lib\gslab_make\private\movedirective.py", line 323, in __init__
    self.parse_file_list()
  File "C:\Users\Zong\template\lib\gslab_make\private\movedirective.py", line 335, in parse_file_list
    self.file_list = convert_to_list(file_list, 'file')
NameError: name 'file_list' is not defined

